apiVersion: apps/v1
kind: Deployment 
metadata:
  # Unique key of the ReplicaSet instance
  name: deployment
spec:
  # 3 Pods should exist at all times.
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      # Run the nginx image
      - name: nginx
        image: httpd
        ports:
        - containerPort: 80
          
